name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build project
        run: |
          bazelisk build project
          bazelisk build project:bin
          bazelisk build project:hex

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build project
        run: |
          bazelisk build project
          bazelisk build project:bin
          bazelisk build project:hex

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build project
        run: |
          bazelisk build project
          bazelisk build project:bin
          bazelisk build project:hex
