name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  macos:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build project
        run: |
          bazelisk build project
          bazelisk build project:bin
          bazelisk build project:hex
