name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  windows:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build project
        run: |
          bazelisk build project:all --platforms=//platforms:pca10040
          bazelisk build project:all --platforms=//platforms:pca10056
          bazelisk build project:all --platforms=//platforms:pca10100
